version: '3'

services:
    socket-proxy:
        image:          tecnativa/docker-socket-proxy
        container_name: socket-proxy
        restart:        unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            CONTAINERS:     1
        networks:
            - proxy

    traefik:
        image:          traefik:v2.1
        container_name: traefik
        restart:        unless-stopped
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml:ro
            - ./dynamic-conf.toml:/etc/traefik/dynamic-conf.toml:ro
            - ./acme/acme.json:/etc/traefik/acme/acme.json
        extra_hosts:
            - "docker-host:172.27.0.1"
        networks:
            - proxy

    apache:
        build:
            context: .
            dockerfile: Dockerfile

        image: c4dt/apache:latest
        container_name: apache
        restart: unless-stopped

        ports:
            - 8081:80

        volumes:
            # FIXME adjust paths
            - /home/cgrigis/C4DT/Projects/showcase:/var/www/showcase:ro
            - /home/cgrigis/C4DT/Projects/incubator:/var/www/incubator:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/demo:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/omniledger:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/stainless:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-ho:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-datasets:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/oh19:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/matrix:ro

        networks:
            proxy:
                aliases:
                    - showcase
                    - incubator
                    - demo
                    - oh19
                    - matrix

networks:
    proxy:
        external: true
