version: '3'

services:
    apache:
        build:
            context: .
            dockerfile: Dockerfile

        image: c4dt/apache:latest
        container_name: apache
        restart: unless-stopped

        ports:
            - 8080:80

        volumes:
            # FIXME adjust paths
            - /home/cgrigis/C4DT/Projects/showcase:/var/www/showcase:ro
            - /home/cgrigis/C4DT/Projects/incubator:/var/www/incubator:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/demo:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/omniledger:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/stainless:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-ho:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-datasets:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/oh19:ro
