version: '3'

services:
    socket-proxy:
        image:          tecnativa/docker-socket-proxy
        container_name: socket-proxy
        restart:        unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            CONTAINERS:     1
        networks:
            - proxy

    traefik:
        image:          traefik:v2.1
        container_name: traefik
        restart:        unless-stopped
        command:
            - "--global.checkNewVersion=true"
            - "--global.sendAnonymousUsage=false"

            - "--log.level=DEBUG"

            - "--entrypoints.web.address=:80"
            - "--entrypoints.web-secure.address=:443"

            - "--providers.docker=true"
            - "--providers.docker.endpoint=tcp://socket-proxy:2375"
            - "--providers.docker.exposedByDefault=false"

            - "--providers.file=true"
            - "--providers.file.filename=/etc/traefik/dynamic-conf.toml"
            - "--providers.file.watch=true"

            - "--certificatesResolvers.sample.acme.email=christian.grigis@epfl.ch"
            - "--certificatesResolvers.sample.acme.storage=/etc/traefik/acme/acme.json"
            - "--certificatesResolvers.sample.acme.httpChallenge.entryPoint=web"

              # - "--api.dashboard=true"
              # - "--api.insecure=true"
        ports:
            - 80:80
            - 443:443
              # - 8080:8080
        volumes:
            - ./dynamic-conf.toml:/etc/traefik/dynamic-conf.toml:ro
            - ./acme/acme.json:/etc/traefik/acme/acme.json
        extra_hosts:
            - "docker-host:172.27.0.1"
        networks:
            - proxy

    apache:
        build:
            context: .
            dockerfile: Dockerfile

        image: c4dt/apache:latest
        container_name: apache
        restart: unless-stopped

        volumes:
            # FIXME adjust paths
            - /home/cgrigis/C4DT/Projects/showcase:/var/www/showcase:ro
            - /home/cgrigis/C4DT/Projects/incubator:/var/www/incubator:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/demo:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/omniledger:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/stainless:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-ho:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/drynx-datasets:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/oh19:ro
            - /home/cgrigis/C4DT/Projects/demo:/var/www/matrix:ro

        labels:
            - "traefik.enable=true"

            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

            - "traefik.http.routers.site-http.rule=HostRegexp(`{subdomain:showcase|incubator|demo|oh19|matrix}.c4dt.org`)"
            - "traefik.http.routers.site-http.entryPoints=web"
            - "traefik.http.routers.site-http.middlewares=redirect-to-https"
            - "traefik.http.routers.site-http.service=httpd"

            - "traefik.http.routers.site-https.rule=HostRegexp(`{subdomain:showcase|incubator|demo|oh19|matrix}.c4dt.org`)"
            - "traefik.http.routers.site-https.entryPoints=web-secure"
            - "traefik.http.routers.site-https.service=httpd"
            - "traefik.http.routers.site-https.tls=true"
            - "traefik.http.routers.site-https.tls.certResolver=sample"

            - "traefik.http.services.httpd.loadbalancer.server.scheme=http"

        networks:
            - proxy

networks:
    proxy:
        external: true
