[http]
  [http.routers]

#     # cryptpad
#     [http.routers.cryptpad-http]
#       rule = "Host(`cryptpad.c4dt.org`)"
#       middlewares = ["redirectToHttps"]
#       service = "cryptpad"
#       entryPoints = ["web"]
# 
#     [http.routers.cryptpad]
#       rule = "Host(`cryptpad.c4dt.org`)"
#       service = "cryptpad"
#       entryPoints = ["web-secure"]
#       [http.routers.cryptpad.tls]
#         certResolver = "sample"
# 
#     [http.routers.matrix-service]
#       rule = "Host(`matrix.c4dt.org`) && Path(`/service`)"
#       service = "matrix"
#       entryPoints = ["web-secure"]
#       middlewares = ["strip-service"]
#       [http.routers.matrix.tls]
#         certResolver = "sample"
# 
#     [http.routers.matrix-main]
#       rule = "Host(`matrix.c4dt.org`) && Path(`/_matrix`)"
#       service = "matrix"
#       entryPoints = ["web-secure"]
#       [http.routers.matrix-main.tls]
#         certResolver = "sample"

    [http.routers.demo-omniledger-api]
      rule = "Host(`demo.c4dt.org`) && PathPrefix(`/omniledger/api`)"
      service = "demo-omniledger-api"
      entryPoints = ["web-secure"]
      middlewares = ["strip-omniledger"]
      priority = 1000
      [http.routers.demo-omniledger-api.tls]
        certResolver = "sample"

    [http.routers.demo-drynx-leader]
      rule = "Host(`demo.c4dt.org`) && Path(`/drynx/leader`)"
      service = "demo-drynx-leader"
      entryPoints = ["web-secure"]
      priority = 1000
      [http.routers.demo-drynx-leader.tls]
        certResolver = "sample"

    [http.routers.jitsi-bind]
      rule = "Host(`jitsi.c4dt.org`) && Path(`/http-bind`)"
      service = "jitsi-bind"
      entryPoints = ["web-secure"]
      priority = 1000
      [http.routers.jitsi-bind.tls]
        certResolver = "sample"

    [http.routers.indie-pocket]
      rule = "Host(`indie.c4dt.org`)"
      service = "indie-pocket"
      entryPoints = ["web-secure"]
      priority = 1000
      [http.routers.indie-pocket.tls]
        certResolver = "sample"

    [http.routers.indie-pocket-www]
      rule = "Host(`indiep.c4dt.org`)"
      service = "indie-pocket-www"
      entryPoints = ["web-secure"]
      priority = 1000
      [http.routers.indie-pocket-www.tls]
        certResolver = "sample"

  [http.middlewares]

    [http.middlewares.strip-omniledger.stripPrefix]
      prefixes = ["/omniledger"]

  [http.services]

#     # cryptpad
#     # Should move to labels in cryptpad docker-compose
#     [http.services.cryptpad]
#       [http.services.cryptpad.loadBalancer]
#         [[http.services.cryptpad.loadBalancer.servers]]
#           url = "http://cryptpad:3000/"
# 
#     # matrix
#     # Should move to labels in matrix docker-compose
#     [http.services.matrix]
#       [http.services.matrix.loadBalancer]
#         [[http.services.matrix.loadBalancer.servers]]
#           url = "http://localhost:8008/"

    # demo omniledger API
    [http.services.demo-omniledger-api]
      [http.services.demo-omniledger-api.loadBalancer]
        [[http.services.demo-omniledger-api.loadBalancer.servers]]
          url = "http://docker-host:4201"

    # demo Drynx leader
    [http.services.demo-drynx-leader]
      [http.services.demo-drynx-leader.loadBalancer]
        [[http.services.demo-drynx-leader.loadBalancer.servers]]
          url = "http://docker-host:4321"

    # Jitsi http-bind
    [http.services.jitsi-bind]
      [http.services.jitsi-bind.loadBalancer]
        [[http.services.jitsi-bind.loadBalancer.servers]]
          url = "http://docker-host:5280"

    # LauzHack server
    [http.services.indie-pocket]
      [http.services.indie-pocket.loadBalancer]
        [[http.services.indie-pocket.loadBalancer.servers]]
          url = "http://docker-host:5678"

    # LauzHack server
    [http.services.indie-pocket-www]
      [http.services.indie-pocket-www.loadBalancer]
        [[http.services.indie-pocket-www.loadBalancer.servers]]
          url = "http://docker-host:5679"
